### PR TITLE
build: support TF 2.7

### PR DESCRIPTION
**Pull request by redeboer**
Note that Python 3.10 is not yet supported:
https://discuss.tensorflow.org/t/support-python-3-10/124

### CODE REVIEW

**Comment by redeboer** [comment]
Motivation: TF 2.7 supports typing-extensions==3.10, which many newer versions of packages like black and pylint require.
https://github.com/ComPWA/tensorwaves/runs/3996801941?check_suite_focus=true#step:9:9

**Comment by jonas-eschle** [comment]
Great, makes sense. I think we can still leave 2.5 and 2.6 as valid versions (as you've done it), there is no breaking feature in 2.7 afai can see

**Review by jonas-eschle — APPROVED** [review]

**Comment by redeboer** [comment]
Do you know why RTD fails?
https://readthedocs.org/projects/phasespace/builds/15190786

**Comment by jonas-eschle** [comment]
I have no idea... that looks really weird. As it is not related seemingly to this PR, we can also merge. I made an issue for it

**Comment by redeboer** [comment]
Thanks!
Could you make a new release?

**Pull request merged**
