### PR TITLE
tests: ensure uproot and awkward consistency, and fix CI

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
OK, almost everything sorted, as expected. The issue with Python 3.10 is, I believe, because uproot4 is explicitly imported, whereas uproot should be imported, and the latter provides 4.x as well as 5.x versions. Let me give this a try ...

**Comment by eduardo-rodrigues** [comment]
Hello @jonas-eschle, I'm trying to get things fixed. I'm afraid there is an inconsistency of requirements, probably now with zfit-physics. Maybe this package is being too restrictive? Can you have a look and advise? Everything else is sorted out.

I would suggest we get a good version releases using uproot4 et al. and then move forward to uproot5 for testing.

**Comment by jonas-eschle** [comment]
There we go, now everything is back to working and fixed and pinned down. Fully agree, we can try out uproot5.
Thanks again for finding and pinging!

**Comment by eduardo-rodrigues** [comment]
Glad to see the CI green again :-).

**Comment by eduardo-rodrigues** [comment]
This warrants a new release, right? Seems necessary IMO. Let me know.

**Pull request merged**
